spring:
  application:
    name: spring-boot-seed

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    timezone: ${DB_TIMEZONE:UTC}
    globally-quoted-identifiers: ${DB_GLOBALLY_QUOTED_IDENTIFIERS:false}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE:false}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    placeholders:
      uuidFunction: uuid_generate_v4()

logging:
  level:
    web: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:INFO}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  setting:
    timezone: ${TIME_ZONE}
