spring:
  application:
    name: spring-boot-seed

  web:
    resources:
      add-mappings: false

  flyway:
    enabled: true
    placeholders:
      uuidFunction: uuid_generate_v4()

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
    timezone: ${DATABASE_TIMEZONE}
    globally-quoted-identifiers: ${DATABASE_GLOBALLY_QUOTED_IDENTIFIERS}

  jpa:
    database-platform: ${DATABASE_DIALECT}
    hibernate:
      ddl-auto: ${DATABASE_HBM2DDL_AUTO}
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  setting:
    timezone: ${TIME_ZONE}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
