spring:
  config:
    import: optional:file:env/.env.dev[.properties]

  devtools:
    restart:
      enabled: true

  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    com.example: DEBUG
